# Form implementation generated from reading ui file 'c:\Users\Vincee Jandayan\Desktop\hotel-management-system\ui_files\upcoming_reservations_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(425, 400)
        Dialog.setMinimumSize(QtCore.QSize(425, 400))
        Dialog.setMaximumSize(QtCore.QSize(425, 400))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.reservations_label = QtWidgets.QLabel(parent=Dialog)
        self.reservations_label.setMinimumSize(QtCore.QSize(0, 40))
        self.reservations_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.reservations_label.setObjectName("reservations_label")
        self.gridLayout.addWidget(self.reservations_label, 0, 0, 1, 1)
        self.reservation_dates_scroll_area = QtWidgets.QScrollArea(parent=Dialog)
        self.reservation_dates_scroll_area.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.reservation_dates_scroll_area.setWidgetResizable(True)
        self.reservation_dates_scroll_area.setObjectName("reservation_dates_scroll_area")
        self.reservation_dates_scroll_area_contents = QtWidgets.QWidget()
        self.reservation_dates_scroll_area_contents.setGeometry(QtCore.QRect(0, 0, 407, 336))
        self.reservation_dates_scroll_area_contents.setObjectName("reservation_dates_scroll_area_contents")
        self.reservation_dates_scroll_area_grid_layout = QtWidgets.QGridLayout(self.reservation_dates_scroll_area_contents)
        self.reservation_dates_scroll_area_grid_layout.setObjectName("reservation_dates_scroll_area_grid_layout")
        self.reservation_dates_scroll_area.setWidget(self.reservation_dates_scroll_area_contents)
        self.gridLayout.addWidget(self.reservation_dates_scroll_area, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.reservations_label.setText(_translate("Dialog", "Reservations of"))
