# Form implementation generated from reading ui file 'add_edit_service_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 245)
        Dialog.setMinimumSize(QtCore.QSize(450, 245))
        Dialog.setMaximumSize(QtCore.QSize(450, 245))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.outer_frame = QtWidgets.QFrame(parent=Dialog)
        self.outer_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.outer_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.outer_frame.setObjectName("outer_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.outer_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(409, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 2)
        self.add_new_service_label = QtWidgets.QLabel(parent=self.outer_frame)
        self.add_new_service_label.setMinimumSize(QtCore.QSize(0, 40))
        self.add_new_service_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.add_new_service_label.setObjectName("add_new_service_label")
        self.gridLayout_3.addWidget(self.add_new_service_label, 1, 0, 1, 2)
        self.cancel_button = QtWidgets.QPushButton(parent=self.outer_frame)
        self.cancel_button.setMinimumSize(QtCore.QSize(0, 30))
        self.cancel_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout_3.addWidget(self.cancel_button, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(409, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 2)
        self.add_service_button = QtWidgets.QPushButton(parent=self.outer_frame)
        self.add_service_button.setMinimumSize(QtCore.QSize(0, 30))
        self.add_service_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.add_service_button.setObjectName("add_service_button")
        self.gridLayout_3.addWidget(self.add_service_button, 4, 1, 1, 1)
        self.contents_frame = QtWidgets.QFrame(parent=self.outer_frame)
        self.contents_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.contents_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contents_frame.setObjectName("contents_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.contents_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rate_label = QtWidgets.QLabel(parent=self.contents_frame)
        self.rate_label.setMinimumSize(QtCore.QSize(125, 40))
        self.rate_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.rate_label.setObjectName("rate_label")
        self.gridLayout_2.addWidget(self.rate_label, 2, 1, 1, 1)
        self.service_name_label = QtWidgets.QLabel(parent=self.contents_frame)
        self.service_name_label.setMinimumSize(QtCore.QSize(0, 40))
        self.service_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.service_name_label.setObjectName("service_name_label")
        self.gridLayout_2.addWidget(self.service_name_label, 2, 0, 1, 1)
        self.rate_spinbox = QtWidgets.QSpinBox(parent=self.contents_frame)
        self.rate_spinbox.setMinimum(1)
        self.rate_spinbox.setMaximum(999999999)
        self.rate_spinbox.setObjectName("rate_spinbox")
        self.gridLayout_2.addWidget(self.rate_spinbox, 4, 1, 1, 1)
        self.service_name_lineedit = QtWidgets.QLineEdit(parent=self.contents_frame)
        self.service_name_lineedit.setObjectName("service_name_lineedit")
        self.gridLayout_2.addWidget(self.service_name_lineedit, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.contents_frame, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.outer_frame, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.add_new_service_label.setText(_translate("Dialog", "Add New Service"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.add_service_button.setText(_translate("Dialog", "Add Service"))
        self.rate_label.setText(_translate("Dialog", "Rate"))
        self.service_name_label.setText(_translate("Dialog", "Service Name"))
