# Form implementation generated from reading ui file 'confirmation_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 150)
        Dialog.setMinimumSize(QtCore.QSize(500, 150))
        Dialog.setMaximumSize(QtCore.QSize(500, 172))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.header_message_label = QtWidgets.QLabel(parent=Dialog)
        self.header_message_label.setMinimumSize(QtCore.QSize(0, 40))
        self.header_message_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.header_message_label.setWordWrap(True)
        self.header_message_label.setObjectName("header_message_label")
        self.gridLayout.addWidget(self.header_message_label, 1, 0, 1, 4)
        self.left_button = QtWidgets.QPushButton(parent=Dialog)
        self.left_button.setMinimumSize(QtCore.QSize(0, 30))
        self.left_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.left_button.setObjectName("left_button")
        self.gridLayout.addWidget(self.left_button, 5, 0, 1, 2)
        self.right_button = QtWidgets.QPushButton(parent=Dialog)
        self.right_button.setMinimumSize(QtCore.QSize(0, 30))
        self.right_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.right_button.setObjectName("right_button")
        self.gridLayout.addWidget(self.right_button, 5, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.subheader_message_label = QtWidgets.QLabel(parent=Dialog)
        self.subheader_message_label.setMinimumSize(QtCore.QSize(0, 0))
        self.subheader_message_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subheader_message_label.setObjectName("subheader_message_label")
        self.gridLayout.addWidget(self.subheader_message_label, 2, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.header_message_label.setText(_translate("Dialog", "Are you sure you want to cancel the reservation process?"))
        self.left_button.setText(_translate("Dialog", "No"))
        self.right_button.setText(_translate("Dialog", "Yes"))
        self.subheader_message_label.setText(_translate("Dialog", "TextLabel"))
