# Form implementation generated from reading ui file 'day_frame.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(231, 62)
        Frame.setMinimumSize(QtCore.QSize(95, 0))
        Frame.setMaximumSize(QtCore.QSize(16777215, 62))
        Frame.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.weekday_name = QtWidgets.QLabel(parent=Frame)
        self.weekday_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weekday_name.setObjectName("weekday_name")
        self.verticalLayout.addWidget(self.weekday_name)
        self.day_number = QtWidgets.QLabel(parent=Frame)
        self.day_number.setMinimumSize(QtCore.QSize(0, 30))
        self.day_number.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.day_number.setObjectName("day_number")
        self.verticalLayout.addWidget(self.day_number)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.weekday_name.setText(_translate("Frame", "TextLabel"))
        self.day_number.setText(_translate("Frame", "TextLabel"))
