# Form implementation generated from reading ui file 'feedback_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 126)
        Dialog.setMinimumSize(QtCore.QSize(500, 120))
        Dialog.setMaximumSize(QtCore.QSize(500, 126))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(-1, 0, -1, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.header_message_label = QtWidgets.QLabel(parent=Dialog)
        self.header_message_label.setMinimumSize(QtCore.QSize(0, 35))
        self.header_message_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.header_message_label.setWordWrap(True)
        self.header_message_label.setObjectName("header_message_label")
        self.gridLayout.addWidget(self.header_message_label, 1, 0, 1, 3)
        self.proceed_button = QtWidgets.QPushButton(parent=Dialog)
        self.proceed_button.setMinimumSize(QtCore.QSize(0, 30))
        self.proceed_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.proceed_button.setObjectName("proceed_button")
        self.gridLayout.addWidget(self.proceed_button, 4, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.subheader_message_label = QtWidgets.QLabel(parent=Dialog)
        self.subheader_message_label.setMinimumSize(QtCore.QSize(0, 20))
        self.subheader_message_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subheader_message_label.setObjectName("subheader_message_label")
        self.gridLayout.addWidget(self.subheader_message_label, 2, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.header_message_label.setText(_translate("Dialog", "Are you sure you want to cancel the reservation process?"))
        self.proceed_button.setText(_translate("Dialog", "Yes"))
        self.subheader_message_label.setText(_translate("Dialog", "TextLabel"))
